// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjQ_vjtpJCp9Gd161VzhtCxMmWU01B_cU',
    appId: '1:70631917955:web:90a8b18e319f4204a94eb6',
    messagingSenderId: '70631917955',
    projectId: 'finny-47c86',
    authDomain: 'finny-47c86.firebaseapp.com',
    storageBucket: 'finny-47c86.firebasestorage.app',
    measurementId: 'G-L44K7E2VH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_bqOdbi7XC3qa6BGkbw18rJqv-4wxVrU',
    appId: '1:70631917955:android:384474c773988794a94eb6',
    messagingSenderId: '70631917955',
    projectId: 'finny-47c86',
    storageBucket: 'finny-47c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO7d2iXWb1XTgKW3wPE9xf77M4EzfGGVg',
    appId: '1:70631917955:ios:6a5929d4b1bfbdc8a94eb6',
    messagingSenderId: '70631917955',
    projectId: 'finny-47c86',
    storageBucket: 'finny-47c86.firebasestorage.app',
    androidClientId: '70631917955-50dimi5btbsjm7h87gais5fcg4m2ftkj.apps.googleusercontent.com',
    iosClientId: '70631917955-b9ccqosuabdp1136qlnln5po65nu1m03.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO7d2iXWb1XTgKW3wPE9xf77M4EzfGGVg',
    appId: '1:70631917955:ios:6a5929d4b1bfbdc8a94eb6',
    messagingSenderId: '70631917955',
    projectId: 'finny-47c86',
    storageBucket: 'finny-47c86.firebasestorage.app',
    androidClientId: '70631917955-50dimi5btbsjm7h87gais5fcg4m2ftkj.apps.googleusercontent.com',
    iosClientId: '70631917955-b9ccqosuabdp1136qlnln5po65nu1m03.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjQ_vjtpJCp9Gd161VzhtCxMmWU01B_cU',
    appId: '1:70631917955:web:a76f8218543da600a94eb6',
    messagingSenderId: '70631917955',
    projectId: 'finny-47c86',
    authDomain: 'finny-47c86.firebaseapp.com',
    storageBucket: 'finny-47c86.firebasestorage.app',
    measurementId: 'G-NRB5W0QSM3',
  );

}